### ISSUE TITLE
TODO: Create entity for processor object

### ISSUE THREAD

**Issue by WaCVPgc0WAPISduQxWZm** [WaCVPgc0WAPISduQxWZm/ToolboxScriptUtilities#1]
The ProgramManagementGetProgramInfo script ability returns a program context object for each slot on the processor. We need to create an entity object to represent the processor, it should have a name field that can correspond to the Section result of the script (which is the room name). It could have an optional field representing the connect address (processor hostname/ip address). Then it should have a collection of ten ProgramContext objects, to represent the ten program slots on a 3-Series processor.

**Comment by pkopysci** [comment]
I've created a Processor class that meets these requirements. It will be added to GitHub by the end of the day.
