### ISSUE TITLE
TODO: ParseResult should return processor entity objects

### ISSUE THREAD

**Issue by WaCVPgc0WAPISduQxWZm** [WaCVPgc0WAPISduQxWZm/ToolboxScriptUtilities#2]
ProgramManagementGetProgramInfoParser.ParseResult() method should return a program entity. See the inline TODO comments. As it parses a successful result line it should create a processor object populated with the program context slots. Instead of being a void method it should return a result.

**Comment by pkopysci** [comment]
I've implemented the Program object return functionality to the ParseResult() method. GitHub will be updated with this change by the end of the day (August 11).
