### ISSUE TITLE
TODO: program should output result as csv

### ISSUE THREAD

**Issue by WaCVPgc0WAPISduQxWZm** [WaCVPgc0WAPISduQxWZm/ToolboxScriptUtilities#3]
The Main program should take the processor objects returned by ParseResult and store them for output.

The output will most likely be imported to Excel as a csv, since that should be fairly easy to format. Each processor should be a row in the csv. Presumably the rows would identify the location of the processor, and then list out the contents of each program context on each slot. If a slot is absent or unregistered its position should be maintained in the csv. In other words, if there is a program registered in slot 1 and slot 10 then the columns for slot 2 - 9 will need to be output as empty strings. The spreadsheet probably doesn't need every single column in the ProgramInfo entity.

Proposed csv layout:
RoomName,Address,S1_SystemName,S1_ProgramFile,S1_IDTag,S1_CompileDate,S2_SystemName... and so on for every slot

**Comment by pkopysci** [comment]
This functionality has been added.
